# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edulution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='user_id',
            field=models.CharField(default=0, max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
